version: "3"

services:
  auth_service:
    image: hmqgg/auth-server
    restart: unless-stopped
    environment:
      - AVATARS__1__AVATAR={{INTERNAL:SUBKEY_AVATAR}}
      - AVATARS__1__SUBKEY__PRIVATEKEY={{INTERNAL:SUBKEY_PRIVATE}}
      - AVATARS__1__SUBKEY__CERTIFICATIONSIGNATURE={{INTERNAL:SUBKEY_SIGNATURE:BASE58}}
      - PROOF__ENDPOINT={{PROMPT:PROOF_ENDPOINT}}
    networks:
      - core_service
    labels:
      - "traefik.http.routers.auth-server-router.rule=Host(`auth.{{INTERNAL:HOST:DOMAIN}}`)"
      - "traefik.http.services.auth-server-service.loadbalancer.server.port=80"

networks:
  core_service:
    external: true
